### ISSUE TITLE
Fix wget download directory for SWI install in maven.yml on GitHub Actions.

### ISSUE THREAD

**Issue by jzalacainllanes** [prolobjectlink/prolobjectlink-jpi-jpl-swi#3]
Fix wget download directory for SWI install in maven.yml on GitHub Actions.

**Comment by somaditya** [comment]
Can you elaborate a bit on the exact fix needed? I checked the url and it seems valid (able to download the tar.gz when hitting url in browser).

**Comment by jzalacainllanes** [comment]
The problem is that the command sudo configure --with-world fails after
wget download and tar command and I am not sure what is the target
directory for these commands. I believe that  wget works fine but i don't
know the target directory for tar command. I think that the command  sudo
configure --with-world fails  because not found the correct SWI directory.

Thanks a lot.

[image: error-swi-6.6.6.png]

[image: error-swi-7.6.4.png]
